<a href="https://colab.research.google.com/github/lnghan/DATA205-Capstone-Project/blob/main/1-ingestion/notebooks/le_capstone_ingestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Han Le
# DATA 205 Project Ingestion Part



---

In [63]:
# Upload all 3 datasets (MC311, Weather, ZIP Code)

from google.colab import files
uploaded = files.upload()

Saving zip_codes.csv to zip_codes.csv

In [2]:
import pandas as pd
import numpy as np
import sqlite3
from datetime import datetime

In [9]:
mc311 = pd.read_csv('mc311_jan2025-apr2026 (1).csv')

In [13]:
conn = sqlite3.connect('mc311.db')
c = conn.cursor()

In [11]:
mc311.to_sql('requests', conn, if_exists='replace', index=False)

675250

In [15]:
# Looking at variable names

pd.read_sql('SELECT * FROM requests LIMIT 1;', conn)

,SR ID,Opened,Closed,Status,Department,Area,Sub-Area,Attached Solution (Topic),Attached Solution SLA Days,City,...,Congressional District,Congressional Member,Council District,Council Member Name,Changed Date,# of Days Open,Within SLA Windows,SLA Yes,SLA No,Request Type
0,1583111101,01/01/2025 12:39:49 AM,01/03/2025 10:08:51 AM,Closed,HHS,SEPH,Emergency Services,First Month's Rent or Security Deposit - HHS,3.0,Damascus,...,6.0,DAVID TRONE (Democrat),7.0,Dawn Luedtke,01/03/2025 03:08:53 PM,2,Yes,1,0,Service Request - Fulfillment

In [19]:
query = '''
SELECT *
FROM requests
WHERE Area IN ('Highway Services', 'Tree maintenance', 'Code Enforcement')
AND 'ZIP Code' IN ('20833', '20866', '20904', '20906', '20850')
'''

mc311_clean = pd.read_sql(query, conn)
display(mc311_clean)

conn.close()

,SR ID,Opened,Closed,Status,Department,Area,Sub-Area,Attached Solution (Topic),Attached Solution SLA Days,City,...,Congressional District,Congressional Member,Council District,Council Member Name,Changed Date,# of Days Open,Within SLA Windows,SLA Yes,SLA No,Request Type
0,1583125970,01/01/2025 10:17:09 AM,01/07/2025 09:35:57 AM,Closed,DHCA,Code Enforcement,None,Housing Complaints,60.0,Silver Spring,...,3.0,JOHN P. SARBANES (Democrat),5.0,Kristin Mink,01/07/2025 02:35:57 PM,3,Yes,1,0,Service Request - Fulfillment
1,1583126709,01/01/2025 04:05:36 PM,01/14/2025 08:48:06 AM,Closed,DOT,Highway Services,Pothole Repair,Pothole Repair,3.0,Silver Spring,...,8.0,JAMIE RASKIN. (Democrat),5.0,Kristin Mink,01/14/2025 01:48:08 PM,8,No,0,1,Service Request - Fulfillment
2,1583126729,01/01/2025 05:16:28 PM,01/02/2025 09:52:41 AM,Closed,DOT,Highway Services,Pothole Repair,Pothole Repair,3.0,Burtonsville,...,3.0,JOHN P. SARBANES (Democrat),5.0,Kristin Mink,01/02/2025 02:52:43 PM,1,Yes,1,0,Service Request - Fulfillment
3,1583154893,01/02/2025 08:30:14 AM,01/02/2025 02:08:35 PM,Closed,DOT,Highway Services,Debris Pickup,Debris Pickup,5.0,Rockville,...,6.0,DAVID TRONE (Democrat),1.0,Andrew Friedson,01/02/2025 07:08:37 PM,0,Yes,1,0,Service Request - Fulfillment
4,1583154935,01/02/2025 08:32:39 AM,01/07/2025 11:35:01 AM,Closed,DOT,Highway Services,Office,Roadway Resurfacing or Repaving,5.0,Brookeville,...,3.0,JOHN P. SARBANES (Democrat),7.0,Dawn Luedtke,01/07/2025 04:35:05 PM,2,Yes,1,0,Service Request - Fulfillment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7275,1617015089,04/04/2026 12:08:53 PM,None,In Progress,DOT,Highway Services,Road Repair,Road Repair,15.0,SILVER SPRING,...,8.0,Jamie Raskin,5.0,Kristin Mink,04/04/2026 04:10:47 PM,4,Yes,1,0,Service Request - Fulfillment
7276,1617015110,04/04/2026 01:50:42 PM,04/08/2026 06:46:47 AM,Closed,DOT,Highway Services,Pothole Repair,Pothole Repair,3.0,SILVER SPRING,...,8.0,Jamie Raskin,6.0,Natali Fani-Gonz?!lez,04/08/2026 10:46:49 AM,3,Yes,1,0,Service Request - Fulfillment
7277,1617063702,04/05/2026 07:24:23 AM,04/06/2026 01:19:06 PM,Closed,DOT,Highway Services,Drainage Repair,Street Drainage Repair,45.0,ROCKVILLE,...,8.0,Jamie Raskin,3.0,Sidney A. Katz,04/06/2026 05:19:08 PM,1,Yes,1,0,Service Request - Fulfillment
7278,1617064269,04/05/2026 01:04:05 PM,04/06/2026 09:50:35 AM,Closed,DHCA,Code Enforcement,None,Housing Complaints,60.0,SILVER SPRING,...,8.0,Jamie Raskin,5.0,Kristin Mink,04/06/2026 01:50:36 PM,1,Yes,1,0,Service Request - Fulfillment
7279,1617064451,04/05/2026 01:08:53 PM,04/06/2026 09:50:37 AM,Closed,DHCA,Code Enforcement,None,Housing Complaints,60.0,SILVER SPRING,...,8.0,Jamie Raskin,5.0,Kristin Mink,04/06/2026 01:50:44 PM,1,Yes,1,0,Service Request - Fulfillment

In [20]:
mc311_clean.to_csv('mc311_clean.csv', index=False)

In [21]:
from google.colab import files
files.download('mc311_clean.csv')

In [59]:
mc311 = pd.read_csv('mc311_clean.csv')
mc311.head()

,SR ID,Opened,Closed,Status,Department,Area,Sub-Area,Attached Solution (Topic),Attached Solution SLA Days,City,...,Congressional District,Congressional Member,Council District,Council Member Name,Changed Date,# of Days Open,Within SLA Windows,SLA Yes,SLA No,Request Type
0,1583125970,01/01/2025 10:17:09 AM,01/07/2025 09:35:57 AM,Closed,DHCA,Code Enforcement,NaN,Housing Complaints,60.0,Silver Spring,...,3.0,JOHN P. SARBANES (Democrat),5.0,Kristin Mink,01/07/2025 02:35:57 PM,3,Yes,1,0,Service Request - Fulfillment
1,1583126709,01/01/2025 04:05:36 PM,01/14/2025 08:48:06 AM,Closed,DOT,Highway Services,Pothole Repair,Pothole Repair,3.0,Silver Spring,...,8.0,JAMIE RASKIN. (Democrat),5.0,Kristin Mink,01/14/2025 01:48:08 PM,8,No,0,1,Service Request - Fulfillment
2,1583126729,01/01/2025 05:16:28 PM,01/02/2025 09:52:41 AM,Closed,DOT,Highway Services,Pothole Repair,Pothole Repair,3.0,Burtonsville,...,3.0,JOHN P. SARBANES (Democrat),5.0,Kristin Mink,01/02/2025 02:52:43 PM,1,Yes,1,0,Service Request - Fulfillment
3,1583154893,01/02/2025 08:30:14 AM,01/02/2025 02:08:35 PM,Closed,DOT,Highway Services,Debris Pickup,Debris Pickup,5.0,Rockville,...,6.0,DAVID TRONE (Democrat),1.0,Andrew Friedson,01/02/2025 07:08:37 PM,0,Yes,1,0,Service Request - Fulfillment
4,1583154935,01/02/2025 08:32:39 AM,01/07/2025 11:35:01 AM,Closed,DOT,Highway Services,Office,Roadway Resurfacing or Repaving,5.0,Brookeville,...,3.0,JOHN P. SARBANES (Democrat),7.0,Dawn Luedtke,01/07/2025 04:35:05 PM,2,Yes,1,0,Service Request - Fulfillment

In [60]:
# Since MC311 dates have time and weather dates do not, I need to fix it in order to merge
mc311['Opened'] = pd.to_datetime(mc311['Opened'],
                                 format='%m/%d/%Y %I:%M:%S %p')

mc311['Closed'] = pd.to_datetime(mc311['Closed'],
                                 format='%m/%d/%Y %I:%M:%S %p')

# Create clean opened and closed columns. Need the opened one for merging and the closed one to calculate response time
mc311['date_opened'] = mc311['Opened'].dt.normalize()
mc311['date_closed'] = mc311['Closed'].dt.normalize()

mc311['response_time'] = (mc311['date_closed'] - mc311['date_opened']).dt.days

# Select variables I will use
mc311 = mc311.drop(columns=['Opened',
                            'Closed',
                            'Changed Date',
                            '# of Days Open',
                            'Sub-Area',
                            'Source',
                            'Request Type',
                            'SLA Yes',
                            'SLA No',
                            'State'])

# Rename variable names for readbility
mc311 = mc311.rename(columns={'SR ID': 'id',
                              'Status': 'status',
                              'Department': 'department',
                              'Area': 'area',
                              'Attached Solution (Topic)': 'area_topic',
                              'City': 'city',
                              'Zip Code': 'zip_code',
                              'Election District': 'election_district',
                              'Maryland State District': 'md_district',
                              'Congressional District': 'congressional_district',
                              'Congressional Member': 'congressional_member',
                              'Council Member Name': 'council_member',
                              'Within SLA Windows': 'within_sla'})

mc311.head()

,id,status,department,area,area_topic,Attached Solution SLA Days,city,zip_code,election_district,md_district,congressional_district,congressional_member,Council District,council_member,within_sla,date_opened,date_closed,response_time
0,1583125970,Closed,DHCA,Code Enforcement,Housing Complaints,60.0,Silver Spring,20904.0,5.0,20.0,3.0,JOHN P. SARBANES (Democrat),5.0,Kristin Mink,Yes,2025-01-01,2025-01-07,6.0
1,1583126709,Closed,DOT,Highway Services,Pothole Repair,3.0,Silver Spring,20904.0,5.0,20.0,8.0,JAMIE RASKIN. (Democrat),5.0,Kristin Mink,No,2025-01-01,2025-01-14,13.0
2,1583126729,Closed,DOT,Highway Services,Pothole Repair,3.0,Burtonsville,20866.0,5.0,14.0,3.0,JOHN P. SARBANES (Democrat),5.0,Kristin Mink,Yes,2025-01-01,2025-01-02,1.0
3,1583154893,Closed,DOT,Highway Services,Debris Pickup,5.0,Rockville,20850.0,4.0,15.0,6.0,DAVID TRONE (Democrat),1.0,Andrew Friedson,Yes,2025-01-02,2025-01-02,0.0
4,1583154935,Closed,DOT,Highway Services,Roadway Resurfacing or Repaving,5.0,Brookeville,20833.0,8.0,14.0,3.0,JOHN P. SARBANES (Democrat),7.0,Dawn Luedtke,Yes,2025-01-02,2025-01-07,5.0

In [39]:
weather = pd.read_csv('maryland_weather.csv')
weather.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,PRCP_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,...,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT03,WT03_ATTRIBUTES
0,USW00093784,"MARYLAND SCIENCE CENTER, MD US",39.2814,-76.6111,6.1,2025-01-01,0.00,",,W,2400",NaN,NaN,...,NaN,NaN,51.0,",,W",42.0,",,W",NaN,NaN,NaN,NaN
1,USW00093784,"MARYLAND SCIENCE CENTER, MD US",39.2814,-76.6111,6.1,2025-01-02,0.00,",,W,2400",NaN,NaN,...,NaN,NaN,42.0,",,W",37.0,",,W",NaN,NaN,NaN,NaN
2,USW00093784,"MARYLAND SCIENCE CENTER, MD US",39.2814,-76.6111,6.1,2025-01-03,0.02,",,W,2400",NaN,NaN,...,NaN,NaN,43.0,",,W",32.0,",,W",NaN,NaN,NaN,NaN
3,USW00093784,"MARYLAND SCIENCE CENTER, MD US",39.2814,-76.6111,6.1,2025-01-04,0.00,",,W,2400",NaN,NaN,...,NaN,NaN,34.0,",,W",27.0,",,W",NaN,NaN,NaN,NaN
4,USW00093784,"MARYLAND SCIENCE CENTER, MD US",39.2814,-76.6111,6.1,2025-01-05,0.00,",,W,2400",NaN,NaN,...,NaN,NaN,34.0,",,W",24.0,",,W",NaN,NaN,NaN,NaN

In [13]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          456 non-null    object
 1   NAME             456 non-null    object
 2   LATITUDE         456 non-null    float64
 3   LONGITUDE        456 non-null    float64
 4   ELEVATION        456 non-null    float64
 5   DATE             456 non-null    object
 6   PRCP             455 non-null    float64
 7   PRCP_ATTRIBUTES  455 non-null    object
 8   SNOW             4 non-null      float64
 9   SNOW_ATTRIBUTES  4 non-null      object
 10  SNWD             4 non-null      float64
 11  SNWD_ATTRIBUTES  4 non-null      object
 12  TAVG             0 non-null      float64
 13  TAVG_ATTRIBUTES  0 non-null      float64
 14  TMAX             455 non-null    float64
 15  TMAX_ATTRIBUTES  455 non-null    object
 16  TMIN             455 non-null    float64
 17  TMIN_ATTRIBUTES  455 non-null    object
 18  WT01             1 non-null      float64
 19  WT01_ATTRIBUTES  1 non-null      object
 20  WT03             3 non-null      float64
 21  WT03_ATTRIBUTES  3 non-null      object
dtypes: float64(12), object(10)
memory usage: 78.5+ KB

In [40]:
# Cleaning weather dataset

# Ensure in datetime format for merging
weather['DATE'] = pd.to_datetime(weather['DATE'])

# Select variables I want to keep
weather = weather[['DATE', 'PRCP', 'TMAX', 'TMIN']]

# Change N/As to 0 so it doesn't mess up analyses
weather['PRCP'] = weather['PRCP'].fillna(0)

# Rename variable names for readbility
weather = weather.rename(columns={'DATE': 'date',
                                  'PRCP': 'prcp',
                                  'TMAX': 'max_temp',
                                  'TMIN': 'min_temp'})

# Calculate average temperature manually since the original dataset had the variable, but no dates had any values
weather['avg_temp'] = (weather['max_temp'] + weather['min_temp']) / 2

weather.head()

        date  prcp  max_temp  min_temp  avg_temp
0 2025-01-01  0.00      51.0      42.0      46.5
1 2025-01-02  0.00      42.0      37.0      39.5
2 2025-01-03  0.02      43.0      32.0      37.5
3 2025-01-04  0.00      34.0      27.0      30.5
4 2025-01-05  0.00      34.0      24.0      29.0

In [61]:
merged = pd.merge(mc311, weather, left_on='date_opened', right_on='date', how='left')
merged.head()

,id,status,department,area,area_topic,Attached Solution SLA Days,city,zip_code,election_district,md_district,...,council_member,within_sla,date_opened,date_closed,response_time,date,prcp,max_temp,min_temp,avg_temp
0,1583125970,Closed,DHCA,Code Enforcement,Housing Complaints,60.0,Silver Spring,20904.0,5.0,20.0,...,Kristin Mink,Yes,2025-01-01,2025-01-07,6.0,2025-01-01,0.0,51.0,42.0,46.5
1,1583126709,Closed,DOT,Highway Services,Pothole Repair,3.0,Silver Spring,20904.0,5.0,20.0,...,Kristin Mink,No,2025-01-01,2025-01-14,13.0,2025-01-01,0.0,51.0,42.0,46.5
2,1583126729,Closed,DOT,Highway Services,Pothole Repair,3.0,Burtonsville,20866.0,5.0,14.0,...,Kristin Mink,Yes,2025-01-01,2025-01-02,1.0,2025-01-01,0.0,51.0,42.0,46.5
3,1583154893,Closed,DOT,Highway Services,Debris Pickup,5.0,Rockville,20850.0,4.0,15.0,...,Andrew Friedson,Yes,2025-01-02,2025-01-02,0.0,2025-01-02,0.0,42.0,37.0,39.5
4,1583154935,Closed,DOT,Highway Services,Roadway Resurfacing or Repaving,5.0,Brookeville,20833.0,8.0,14.0,...,Dawn Luedtke,Yes,2025-01-02,2025-01-07,5.0,2025-01-02,0.0,42.0,37.0,39.5

In [69]:
zips = pd.read_csv("zip_codes.csv")

zips.info()
zips.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 42 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OBJECTID_1    468 non-null    int64
 1   ZCTA5CE10     468 non-null    int64
 2   FIRST_STAT    468 non-null    int64
 3   FIRST_GEOI    468 non-null    int64
 4   FIRST_CLAS    468 non-null    object
 5   FIRST_MTFC    468 non-null    object
 6   FIRST_FUNC    468 non-null    object
 7   ZCTA5N        468 non-null    int64
 8   STATE         468 non-null    int64
 9   AREALAND      468 non-null    int64
 10  AREAWATR      468 non-null    int64
 11  POP100        468 non-null    int64
 12  HU100         468 non-null    int64
 13  NHW           468 non-null    int64
 14  NHB           468 non-null    int64
 15  NHAI          468 non-null    int64
 16  NHA           468 non-null    int64
 17  NHNH          468 non-null    int64
 18  NHO           468 non-null    int64
 19  NHT           468 non-null    int64
 20  HISP          468 non-null    int64
 21  PNHW          468 non-null    float64
 22  PNHB          468 non-null    float64
 23  PNHAI         468 non-null    float64
 24  PNHA          468 non-null    float64
 25  PNHNH         468 non-null    float64
 26  PNHO          468 non-null    float64
 27  PNHT          468 non-null    float64
 28  PHISP         468 non-null    float64
 29  POP65_        468 non-null    int64
 30  PCTPOP65_     468 non-null    float64
 31  MEDAGE        468 non-null    float64
 32  VACNS         468 non-null    int64
 33  PVACNS        468 non-null    float64
 34  PHOWN         468 non-null    float64
 35  PWOMORT       468 non-null    float64
 36  PRENT         468 non-null    float64
 37  PLT18SP       468 non-null    float64
 38  REPORT_2_P    468 non-null    object
 39  REPORT_9_P    468 non-null    object
 40  Shape_Length  468 non-null    float64
 41  Shape_Area    468 non-null    float64
dtypes: float64(17), int64(20), object(5)
memory usage: 153.7+ KB

,OBJECTID_1,ZCTA5CE10,FIRST_STAT,FIRST_GEOI,FIRST_CLAS,FIRST_MTFC,FIRST_FUNC,ZCTA5N,STATE,AREALAND,...,VACNS,PVACNS,PHOWN,PWOMORT,PRENT,PLT18SP,REPORT_2_P,REPORT_9_P,Shape_Length,Shape_Area
0,1,20601,24,2420601,B5,G6350,S,20601,24,115635266,...,376,4.3,71.1,11.2,19.9,30.4,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,89500.303353,1.903175e+08
1,2,20602,24,2420602,B5,G6350,S,20602,24,35830723,...,769,7.9,59.7,9.0,34.4,43.6,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,42220.214377,5.930458e+07
2,3,20603,24,2420603,B5,G6350,S,20603,24,44239637,...,531,5.1,73.8,4.7,22.6,29.9,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,50682.962600,7.295967e+07
3,4,20606,24,2420606,B5,G6350,S,20606,24,7501011,...,15,6.5,49.7,39.3,18.1,31.2,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,41458.263845,1.221117e+07
4,5,20607,24,2420607,B5,G6350,S,20607,24,54357590,...,172,4.9,83.1,10.3,7.4,22.1,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,58903.058735,8.962880e+07

In [70]:
keep = [20833, 20866, 20904, 20906, 20850]

zips = zips[zips['ZCTA5CE10'].isin(keep)]
zips.head()

,OBJECTID_1,ZCTA5CE10,FIRST_STAT,FIRST_GEOI,FIRST_CLAS,FIRST_MTFC,FIRST_FUNC,ZCTA5N,STATE,AREALAND,...,VACNS,PVACNS,PHOWN,PWOMORT,PRENT,PLT18SP,REPORT_2_P,REPORT_9_P,Shape_Length,Shape_Area
118,119,20833,24,2420833,B5,G6350,S,20833,24,49836780,...,65,2.6,80.8,13.7,6.4,12.2,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,82888.914678,8.365230e+07
124,125,20850,24,2420850,B5,G6350,S,20850,24,36523908,...,824,4.3,49.8,17.9,39.4,20.0,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,59214.685310,6.104587e+07
133,134,20866,24,2420866,B5,G6350,S,20866,24,18304211,...,178,3.8,69.8,10.0,22.4,31.9,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,35039.859318,3.054497e+07
151,152,20904,24,2420904,B5,G6350,S,20904,24,35402513,...,937,4.4,42.3,21.5,46.2,35.7,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,46843.065568,5.897200e+07
153,154,20906,24,2420906,B5,G6350,S,20906,24,31358675,...,1437,5.6,46.3,30.3,33.5,34.0,http://mdpgis.mdp.state.md.us/Census2010/PDF/0...,http://mdpgis.mdp.state.md.us/census2010/PDF/0...,46257.926758,5.245246e+07

In [ ]:
# I don't want to merge census data to main dataset as I think it will complicate things.